acceptable_licenses = ["CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
                       "Creative Commons Attribution 2.5 India (CC BY 2.5 IN)",
                       "Creative Commons Attribution 3.0 License",
                       "Public Domain",
                       "Other - Direct Permission",
                       "Creative Commons Attribution 4.0 International (CC BY 4.0)",
                       "Creative Commons Attribution 4.0 (CC BY 4.0)",
                       "Creative Commons Attribution 3.0 Intergovernmental Organisations (CC BY 3.0 IGO)",
                       "Data license Germany - Attribution - Version 2.0",
                       "MIMU Data License (MIMU)",
                       "Open Data Commons Attribution License 1.0",
                       "Open Government Licence v3.0",
                       "Open Government Licence v1.0",
                       "Other - Humanitarian",
                       "Singapore Open Data License Version 1.0",
                       "National Institute of Statistics (INE) Data License)",
                       "Korea Open Government License Type 1 (Source Indication)",
                       "Open Data Commons Public Domain Dedication and License (PDDL) v1.0",
                       "UN SALB Data License",
                       "Attribution 2.5 Denmark (CC BY 2.5 DK)",
                       "Creative Commons Attribution 2.5 Generic",
                       "Pixabay License for Content",
                       "Etalab Open License 2.0",
                       "Attribuzione 3.0 Italia (CC BY 3.0 IT)",
                       "Federal Office of Topography swisstopo License",
                       "Open Government Canada 2.0",
                       "Sierra Leone Open License Agreement"
]
